// <auto-generated />
using CityInfo.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityInfo.API.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    partial class CityInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("CityInfo.API.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Stolica",
                            Name = "Warszawa"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Piękne miasto położone nad morzem",
                            Name = "Gdanśk"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Miasto Królów Polskich",
                            Name = "Kraków"
                        });
                });

            modelBuilder.Entity("CityInfo.API.Entities.PointOfIntrest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointsOfIntrest");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 2,
                            Description = "Najokazalsza i najcenniejsza budowla świecka dawnego Gdańska, siedziba władz miasta. Budowany był od 1379 do 1492 roku.",
                            Name = "Ratusz Głównego Miasta"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            Description = "Przez wiele lat był jednym z najwspanialszych tego typu obiektów w Europie północnej.",
                            Name = "Dwór Artusa"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 3,
                            Description = "Słynna bazylika z dwiema wieżami",
                            Name = "Bazylika Mariacka"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 3,
                            Description = "średniowieczny zamek królewski",
                            Name = "Zamek królewski na wawelu"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 2,
                            Description = "to jeden z najpiękniejszych kompleksów ogrodowych nie tylko w Polsce, ale i w Europie ",
                            Name = "Łazienki Królewskie"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 2,
                            Description = "To tak naprawdę wizytówka stolicy i najwyższy budynek w Polsce (ma 237 m wysokości) ",
                            Name = "Pałac Kultury i Nauki"
                        });
                });

            modelBuilder.Entity("CityInfo.API.Entities.PointOfIntrest", b =>
                {
                    b.HasOne("CityInfo.API.Entities.City", "City")
                        .WithMany("PointOfIntrests")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CityInfo.API.Entities.City", b =>
                {
                    b.Navigation("PointOfIntrests");
                });
#pragma warning restore 612, 618
        }
    }
}
